version: '3.8'

services:
  # --- 1. 数据库 & 缓存 ---
  postgres:
    image: postgres:latest
    container_name: software-engineering-5-postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Shanghai
    ports:
      - "33306:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql
    networks:
      - software-engineering-net
    restart: always

#  redis:
#    image: redis:latest
#    container_name: software-engineering-5-redis
#    environment:
#      TZ: Asia/Shanghai
#    networks:
#      - software-engineering-net
#    restart: always

  # --- 2. 后端服务 ---
  backend:
    build:
      context: .
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
        GRADLE_OPTS: ${GRADLE_OPTS}
    container_name: software-engineering-5-backend
    ports:
      - "18080:8080"
    env_file:
      - .env
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      # 把容器内的 logs 目录映射到宿主机的 ./logs 目录
      - ./backend_logs:/app/logs
    depends_on:
      - postgres
#      - redis
    networks:
      - software-engineering-net
    restart: always

  # --- 4. 网关 (Nginx) ---
#  nginx:
#    image: nginx:alpine
#    container_name: software-engineering-5-nginx
#    ports:
#      - "80:80" # 唯一对外暴露端口
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - backend
#    networks:
#      - software-engineering-net
#    restart: always

networks:
  software-engineering-net:
    driver: bridge