spring:
  datasource:
    url: ${DEV_DATABASE_URL}
    username: ${DEV_DATABASE_USERNAME}
    password: ${DEV_DATABASE_PASSWORD}
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      password: ${DEV_REDIS_PASSWORD}
      database: ${DEV_REDIS_DATABASE}
  sql:
    init:
      mode: always
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.szu.afternoon5.softwareengineeringbackend.service.MetricsService: DEBUG

wx:
  test-jscode: TEST_TEST_ONLY_JSCODE

jwt:
  secret-key: a-string-secret-at-least-256-bits-long


ali:
  oss:
    endpoint: ${ALI_OSS_ENDPOINT}
    access-key-id: ${ALI_OSS_ACCESS_KEY_ID}
    access-key-secret: ${ALI_OSS_ACCESS_KEY_SECRET}
    bucket-name: ${ALI_OSS_BUCKET_NAME}
    cdn-host: ${ALI_OSS_CDN_HOST}

builtin-super-admin:
  username: superadmin
  password: superadmin
